version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: calagem
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calagem
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data:
